###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:9.6-alpine
      container_name: moleo-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=moleo
      ports:
          - '5433:5432'

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: moleo-elasticsearch

    webserver:
      image: nginx:latest
      container_name: moleo-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: moleo-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
          - postgres

